version: '3'

services:
  swoole:
    image: "${IMAGE}"
    environment:
      - HOST
      - HOSTNAME
      - PORT
    command: php /workdir/app/index.php start
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./:/workdir
      - ./.env:/workdir/app/.env
